version: "3.9"

services:
  database:
    image: postgres:alpine
    container_name: transcendence_db
    hostname: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: "redis:alpine"
    container_name: transcendence_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: