# Generated by Django 4.1 on 2024-02-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_channel_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='password',
        ),
    ]
