# Generated by Django 4.1 on 2024-02-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_channel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
