# Generated by Django 4.2.11 on 2024-05-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_channel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='updatedAt',
        ),
    ]
