# Generated by Django 5.0.2 on 2024-05-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='received_invite',
            field=models.BooleanField(default=False),
        ),
    ]
