# Generated by Django 4.2.13 on 2024-06-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_participants_alter_participant_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments', to='tournament.participant'),
        ),
    ]
