# Generated by Django 5.0.2 on 2024-06-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_participants_alter_participant_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
