# Generated by Django 4.1 on 2024-06-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_participant_ready'),
        ('tournament', '0005_alter_tournament_participants'),
    ]

    operations = [
    ]
