# Generated by Django 4.1 on 2024-05-06 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatarimageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
