# Generated by Django 5.0.2 on 2024-05-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatarimageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_chevre_verte_award',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trophies',
            field=models.IntegerField(default=0),
        ),
    ]
