# Generated by Django 5.0.2 on 2024-05-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_blocked_users'),
        ('users', '0003_customuser_has_chevre_verte_award_and_more'),
    ]

    operations = [
    ]
