# Generated by Django 4.1 on 2023-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='channelsAsAdmin',
            field=models.ManyToManyField(related_name='administered_by', to='users.channel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='channelsAsMember',
            field=models.ManyToManyField(related_name='member', to='users.channel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='channelsAsOwner',
            field=models.ManyToManyField(related_name='owned_by', to='users.channel'),
        ),
    ]
