# Generated by Django 4.1 on 2024-01-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_channelsasadmin_and_more'),
        ('users', '0005_customuser_friends_and_more'),
    ]

    operations = [
    ]
